openapi: 3.0.0
info:
  title: Users
  version: '1.0'
servers:
  - url: 'https://st-api.gleads.io'
    description: DEV API
paths:
  /api/users/login:
    parameters: []
    post:
      summary: User authentication
      operationId: post-api-users-login
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  _key:
                    type: string
                    minLength: 1
                  _id:
                    type: string
                    minLength: 1
                  _rev:
                    type: string
                    minLength: 1
                  user_id:
                    type: string
                    minLength: 1
                  session_token:
                    type: string
                    minLength: 1
                  expired:
                    type: boolean
                  meta:
                    type: object
                    required:
                      - userAgent
                      - clientIp
                      - deviceHash
                    properties:
                      userAgent:
                        type: string
                        minLength: 1
                      clientIp:
                        type: string
                        minLength: 1
                      deviceHash:
                        type: string
                        minLength: 1
                  session_unlocked:
                    type: string
                    minLength: 1
                  verifications_access:
                    type: object
                    required:
                      - code
                      - critical
                      - description
                    properties:
                      code:
                        type: number
                      critical:
                        type: boolean
                      description:
                        type: string
                        minLength: 1
                  device_access:
                    type: object
                    required:
                      - code
                      - critical
                      - description
                    properties:
                      code:
                        type: number
                      critical:
                        type: boolean
                      description:
                        type: string
                        minLength: 1
                      verification_token: {}
                  user:
                    type: object
                    required:
                      - _key
                      - _id
                      - _rev
                      - email
                      - _created
                      - _updated
                      - devices
                      - verifications
                    properties:
                      _key:
                        type: string
                        minLength: 1
                      _id:
                        type: string
                        minLength: 1
                      _rev:
                        type: string
                        minLength: 1
                      email:
                        type: string
                        minLength: 1
                      _created:
                        type: string
                        minLength: 1
                      _updated:
                        type: string
                        minLength: 1
                      devices:
                        type: object
                      verifications:
                        type: object
                        required:
                          - email
                        properties:
                          email:
                            type: object
                            required:
                              - _key
                              - code
                              - gateway
                              - resolved
                              - submited
                              - token
                              - type
                              - verified
                              - user_id
                              - _id
                              - _rev
                            properties:
                              _key:
                                type: string
                                minLength: 1
                              code:
                                type: string
                                minLength: 1
                              gateway:
                                type: string
                                minLength: 1
                              resolved:
                                type: string
                                minLength: 1
                              submited:
                                type: string
                                minLength: 1
                              token:
                                type: string
                                minLength: 1
                              type:
                                type: string
                                minLength: 1
                              verified:
                                type: boolean
                              user_id:
                                type: string
                                minLength: 1
                              _id:
                                type: string
                                minLength: 1
                              _rev:
                                type: string
                                minLength: 1
                required:
                  - _key
                  - _id
                  - _rev
                  - user_id
                  - session_token
                  - expired
                  - meta
                  - session_unlocked
                  - verifications_access
                  - device_access
                  - user
              examples:
                Valid login:
                  value:
                    _key: fdeabcf1-6d25-406a-830e-8980f85fc688
                    _id: sessions/fdeabcf1-6d25-406a-830e-8980f85fc688
                    _rev: _cNBR9A2---
                    user_id: '84304'
                    session_token: fdeabcf1-6d25-406a-830e-8980f85fc688
                    expired: false
                    meta:
                      userAgent: PostmanRuntime/7.26.8
                      clientIp: 45.12.221.18
                      deviceHash: UG9zdG1hblJ1bnRpbWUvNy4yNi44LS00NS4xMi4yMjEuMTg=
                    session_unlocked: '2021-04-20T19:48:47+00:00'
                    verifications_access:
                      code: 2000
                      critical: false
                      description: Verifications completed
                    device_access:
                      code: 1000
                      critical: false
                      description: User access granted
                      verification_token: null
                    user:
                      _key: '84304'
                      _id: users/84304
                      _rev: _cLatWZ----
                      email: gleadstesting-v8o20jpo79dojs8e5mvea@gleads.io
                      _created: '2021-04-15T20:17:02+00:00'
                      _updated: '2021-04-15T20:17:02+00:00'
                      devices:
                        UG9zdG1hblJ1bnRpbWUvNy4yNi44LS00NS4xMi4yMjEuMTg=:
                          id: null
                          verified: true
                          date: '2021-04-15T20:17:02+00:00'
                      verifications:
                        email:
                          _key: fafc0af6-9323-4d8b-ab1f-0426ba6fab05
                          code: bb028571-05f2-4a71-949a-1ff9c97dc42c
                          gateway: email
                          resolved: '2021-04-15T20:17:03+00:00'
                          submited: '2021-04-15T20:17:02+00:00'
                          token: fafc0af6-9323-4d8b-ab1f-0426ba6fab05
                          type: verifications
                          verified: true
                          user_id: '84304'
                          _id: verifications/fafc0af6-9323-4d8b-ab1f-0426ba6fab05
                          _rev: _cLasCTa---
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  name:
                    type: string
                    minLength: 1
                  message:
                    type: string
                    minLength: 1
                  code:
                    type: number
                  type:
                    type: string
                    minLength: 1
                  data:
                    type: object
                    properties:
                      msg:
                        type: string
                        minLength: 1
                    required:
                      - msg
                required:
                  - name
                  - message
                  - code
                  - type
                  - data
              examples:
                Invalid credentials:
                  value:
                    name: AuthInvalidCredentialsError
                    message: Authentication error
                    code: 401
                    type: AUTH_ERROR
                    data:
                      msg: Invalid credentials
        '422':
          description: Form validation error
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  name:
                    type: string
                    minLength: 1
                  message:
                    type: string
                    minLength: 1
                  code:
                    type: number
                  type:
                    type: string
                    minLength: 1
                  data:
                    type: array
                    uniqueItems: true
                    minItems: 1
                    items:
                      required:
                        - type
                        - message
                        - field
                        - nodeID
                        - action
                      properties:
                        type:
                          type: string
                          minLength: 1
                        message:
                          type: string
                          minLength: 1
                        field:
                          type: string
                          minLength: 1
                        nodeID:
                          type: string
                          minLength: 1
                        action:
                          type: string
                          minLength: 1
                required:
                  - name
                  - message
                  - code
                  - type
                  - data
              examples:
                Validation error:
                  value:
                    name: ValidationError
                    message: Parameters validation error!
                    code: 422
                    type: VALIDATION_ERROR
                    data:
                      - type: required
                        message: The 'email' field is required.
                        field: email
                        nodeID: vps-2347f1db.vps.ovh.net.novalocal-549873
                        action: users.login
                      - type: required
                        message: The 'password' field is required.
                        field: password
                        nodeID: vps-2347f1db.vps.ovh.net.novalocal-549873
                        action: users.login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
            examples:
              Valid authentication:
                value:
                  email: test@test.com
                  password: Aa5685855
      description: User authentication
      parameters:
        - schema:
            type: string
          in: header
          name: Content-Type
          description: application/json
  /user:
    post:
      summary: Create New User
      operationId: post-user
      responses:
        '200':
          description: User Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                New User Bob Fellow:
                  value:
                    id: 12
                    firstName: Bob
                    lastName: Fellow
                    email: bob.fellow@gmail.com
                    dateOfBirth: '1996-08-24'
                    emailVerified: false
                    createDate: '2020-11-18'
        '400':
          description: Missing Required Information
        '409':
          description: Email Already Taken
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                dateOfBirth:
                  type: string
                  format: date
              required:
                - firstName
                - lastName
                - email
                - dateOfBirth
            examples:
              Create User Bob Fellow:
                value:
                  firstName: Bob
                  lastName: Fellow
                  email: bob.fellow@gmail.com
                  dateOfBirth: '1996-08-24'
        description: Post the necessary fields for the API to create a new user.
      description: Create a new user.
components:
  schemas:
    User:
      title: User
      type: object
      description: ''
      x-examples:
        Alice Smith:
          id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
          format: email
        dateOfBirth:
          type: string
          format: date
          example: '1997-10-31'
        emailVerified:
          type: boolean
          description: Set to true if the user's email has been verified.
        createDate:
          type: string
          format: date
          description: The date that the user was created.
      required:
        - id
        - firstName
        - lastName
        - email
        - emailVerified
  securitySchemes: {}
